# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messages/argument.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/messages/argument.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dproto/messages/argument.proto\"\x18\n\x08\x41rgument\x12\x0c\n\x04\x61rgs\x18\x01 \x03(\tb\x06proto3')
)




_ARGUMENT = _descriptor.Descriptor(
  name='Argument',
  full_name='Argument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='args', full_name='Argument.args', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['Argument'] = _ARGUMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Argument = _reflection.GeneratedProtocolMessageType('Argument', (_message.Message,), dict(
  DESCRIPTOR = _ARGUMENT,
  __module__ = 'proto.messages.argument_pb2'
  # @@protoc_insertion_point(class_scope:Argument)
  ))
_sym_db.RegisterMessage(Argument)


# @@protoc_insertion_point(module_scope)
