# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: xcodebuild/xcodebuild.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import xcodebuild.xcodebuild_pb2


class XcodeBase(abc.ABC):

    @abc.abstractmethod
    async def Build(self, stream):
        pass

    @abc.abstractmethod
    async def Select(self, stream):
        pass

    def __mapping__(self):
        return {
            '/services.Xcode/Build': grpclib.const.Handler(
                self.Build,
                grpclib.const.Cardinality.UNARY_UNARY,
                xcodebuild.xcodebuild_pb2.Argument,
                xcodebuild.xcodebuild_pb2.Output,
            ),
            '/services.Xcode/Select': grpclib.const.Handler(
                self.Select,
                grpclib.const.Cardinality.UNARY_UNARY,
                xcodebuild.xcodebuild_pb2.Argument,
                xcodebuild.xcodebuild_pb2.Output,
            ),
        }


class XcodeStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Build = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.Xcode/Build',
            xcodebuild.xcodebuild_pb2.Argument,
            xcodebuild.xcodebuild_pb2.Output,
        )
        self.Select = grpclib.client.UnaryUnaryMethod(
            channel,
            '/services.Xcode/Select',
            xcodebuild.xcodebuild_pb2.Argument,
            xcodebuild.xcodebuild_pb2.Output,
        )
