# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xcodebuild/xcodebuild.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xcodebuild/xcodebuild.proto',
  package='services',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bxcodebuild/xcodebuild.proto\x12\x08services\"\x18\n\x08\x41rgument\x12\x0c\n\x04\x61rgs\x18\x01 \x03(\t\"9\n\x06Output\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x0e\n\x06stderr\x18\x03 \x01(\t2j\n\x05Xcode\x12/\n\x05\x42uild\x12\x12.services.Argument\x1a\x10.services.Output\"\x00\x12\x30\n\x06Select\x12\x12.services.Argument\x1a\x10.services.Output\"\x00\x62\x06proto3')
)




_ARGUMENT = _descriptor.Descriptor(
  name='Argument',
  full_name='services.Argument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='args', full_name='services.Argument.args', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=65,
)


_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='services.Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retcode', full_name='services.Output.retcode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stdout', full_name='services.Output.stdout', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stderr', full_name='services.Output.stderr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['Argument'] = _ARGUMENT
DESCRIPTOR.message_types_by_name['Output'] = _OUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Argument = _reflection.GeneratedProtocolMessageType('Argument', (_message.Message,), dict(
  DESCRIPTOR = _ARGUMENT,
  __module__ = 'xcodebuild.xcodebuild_pb2'
  # @@protoc_insertion_point(class_scope:services.Argument)
  ))
_sym_db.RegisterMessage(Argument)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUT,
  __module__ = 'xcodebuild.xcodebuild_pb2'
  # @@protoc_insertion_point(class_scope:services.Output)
  ))
_sym_db.RegisterMessage(Output)



_XCODE = _descriptor.ServiceDescriptor(
  name='Xcode',
  full_name='services.Xcode',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=126,
  serialized_end=232,
  methods=[
  _descriptor.MethodDescriptor(
    name='Build',
    full_name='services.Xcode.Build',
    index=0,
    containing_service=None,
    input_type=_ARGUMENT,
    output_type=_OUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Select',
    full_name='services.Xcode.Select',
    index=1,
    containing_service=None,
    input_type=_ARGUMENT,
    output_type=_OUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_XCODE)

DESCRIPTOR.services_by_name['Xcode'] = _XCODE

# @@protoc_insertion_point(module_scope)
